version: '3.5'


services:
  consignment:
    restart: always
    build: ./shippy-service-consignment
    depends_on:
      - datastore
      - vessel
    ports:
      - 50051:50051
    environment: 
      MICRO_SERVER_ADDRESS: ":50051"
      DB_HOST: "mongodb://datastore:27017ls"
  
  vessel:
    restart: always
    build: ./shippy-service-vessel
    ports:
      - 50052:50051
    environment: 
      MICRO_SERVER_ADDRESS: ":50051"
      DB_HOST: "mongodb://datastore:27017"

  cli:
    build: ./shippy-cli-consignment